# Generated by Django 5.0.2 on 2025-05-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web_movil_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='terminos',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
