# Generated by Django 5.0.2 on 2025-05-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web_movil_api', '0002_profiles_ciudad_profiles_edad_profiles_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='terminos',
            new_name='terminos_condiciones',
        ),
    ]
